Repository wieslawsoltes/Dock, pull requests merged in 2022-11, with the labels that each got.

#251 Fix HostWindow drag on linux/macos
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml.cs
Labels: size/XS

#254 Use pointer events instead of DragDelta
  src/Dock.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
Labels: size/M

#255 Refactor pins
  samples/AvaloniaDemo.Base/ViewModels/DockFactory.cs
  src/Dock.Avalonia/Controls/DockControl.axaml
  src/Dock.Avalonia/Controls/DockDockControl.axaml
  src/Dock.Avalonia/Controls/DockDockControl.axaml.cs
  src/Dock.Avalonia/Controls/DockPanelSplitter.axaml
  src/Dock.Avalonia/Controls/DockPanelSplitter.axaml.cs
  src/Dock.Avalonia/Controls/DocumentContentControl.axaml
  src/Dock.Avalonia/Controls/DocumentContentControl.axaml.cs
  src/Dock.Avalonia/Controls/DocumentDockControl.axaml
  src/Dock.Avalonia/Controls/DocumentDockControl.axaml.cs
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ProportionalDockControl.axaml
  src/Dock.Avalonia/Controls/ProportionalDockControl.axaml.cs
  src/Dock.Avalonia/Controls/RootDockControl.axaml
  src/Dock.Avalonia/Controls/RootDockControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Controls/ToolContentControl.axaml
  src/Dock.Avalonia/Controls/ToolContentControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolDockControl.axaml
  src/Dock.Avalonia/Controls/ToolDockControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolPinnedControl.axaml
  src/Dock.Avalonia/Controls/ToolPinnedControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
  src/Dock.Avalonia/Themes/DockFluentTheme.axaml
  src/Dock.Avalonia/Themes/DockSimpleTheme.axaml
  src/Dock.Model.Avalonia/Controls/RootDock.cs
  src/Dock.Model.Avalonia/Core/DockBase.cs
  src/Dock.Model.Mvvm/Controls/RootDock.cs
  src/Dock.Model.Mvvm/Core/DockBase.cs
  src/Dock.Model.ReactiveUI/Controls/RootDock.cs
  src/Dock.Model.ReactiveUI/Core/DockBase.cs
  src/Dock.Model/Controls/IRootDock.cs
  src/Dock.Model/Core/IDock.cs
  src/Dock.Model/FactoryBase.cs
  src/Dock.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml
Labels: size/XXL

#256 Avalonia model refactoring
  samples/DemoDebug/DockFactory.cs
  samples/DemoPerspectives/DockFactory.cs
  samples/DemoXaml/MainView.axaml
  samples/DemoXaml/MainView.axaml.cs
  samples/Notepad/ViewModels/NotepadFactory.cs
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Model.Avalonia/Controls/DockDock.cs
  src/Dock.Model.Avalonia/Controls/Document.cs
  src/Dock.Model.Avalonia/Controls/DocumentDock.cs
  src/Dock.Model.Avalonia/Controls/DocumentTemplate.cs
  src/Dock.Model.Avalonia/Controls/ProportionalDock.cs
  src/Dock.Model.Avalonia/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.Avalonia/Controls/RootDock.cs
  src/Dock.Model.Avalonia/Controls/Tool.cs
  src/Dock.Model.Avalonia/Controls/ToolDock.cs
  src/Dock.Model.Avalonia/Core/DockState.cs
  src/Dock.Model.Avalonia/Core/DockableBase.cs
  src/Dock.Model/Controls/IDocumentDockContent.cs
  src/Dock.Model/Controls/IDocumentTemplate.cs
  src/Dock.Model/Core/IDockControl.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/DockManager.cs
  src/Dock.Model/FactoryBase.cs
Labels: size/L
