Repository wieslawsoltes/Dock, pull requests merged in 2025-09, with the labels that each got.

#909 Only change the active tab on close, if the closed tab was the active tab.
  src/Dock.Model/FactoryBase.Dockable.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryDockableLifecycleTests.cs
Labels: size/M

#914 TabStripItems double click obeys CanCloseLastDockable
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml.cs
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml.cs
Labels: size/S

#901 Add DockFluentCodeOnlySample sample
  Dock.sln
  samples/DockFluentCodeOnlySample/DockFluentCodeOnlySample.csproj
  samples/DockFluentCodeOnlySample/Program.cs
Labels: size/L
