Repository wieslawsoltes/Dock, pull requests merged in 2025-07, with the labels that each got.

#469 Fix drag preview float status
  src/Dock.Avalonia/Internal/DockControlState.cs
Labels: size/XS, codex

#471 Improve drag preview UI
  src/Dock.Avalonia/Controls/DragPreviewControl.axaml
Labels: size/S, codex

#480 Add CanResize option for proportional splitters
  docs/dock-reference.md
  samples/DockMvvmSample/ViewModels/DockFactory.cs
  samples/DockReactiveUISample/ViewModels/DockFactory.cs
  src/Dock.Avalonia/Controls/DockControl.axaml
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
  src/Dock.Model.Avalonia/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.Mvvm/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.ReactiveUI/Controls/ProportionalDockSplitter.cs
  src/Dock.Model/Controls/IProportionalDockSplitter.cs
  tests/Dock.Model.Mvvm.UnitTests/FactoryTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/FactoryTests.cs
Labels: size/M, codex

#475 Add themable drag preview window
  src/Dock.Avalonia/Controls/DragPreviewWindow.axaml
  src/Dock.Avalonia/Controls/DragPreviewWindow.axaml.cs
  src/Dock.Avalonia/Internal/DragPreviewHelper.cs
  src/Dock.Avalonia/Themes/DockFluentTheme.axaml
  src/Dock.Avalonia/Themes/DockSimpleTheme.axaml
Labels: size/M, codex

#487 Add sizing guide for Dock
  docs/README.md
  docs/dock-sizing.md
Labels: size/M, codex

#491 Improve Dock docs
  docs/README.md
  docs/dock-dockable-properties.md
  docs/dock-faq.md
  docs/dock-settings.md
  docs/dock-windows.md
Labels: size/M, codex

#495 Add documentation for dockable tracking methods
  docs/dock-advanced.md
  docs/dock-reference.md
Labels: size/M, codex

#493 Add root control tracking
  src/Dock.Avalonia/Controls/DockableControl.cs
  src/Dock.Model.Avalonia/Factory.cs
  src/Dock.Model.Mvvm/Factory.cs
  src/Dock.Model.ReactiveUI/Factory.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Factory.cs
Labels: size/M, codex

#494 Fix ProportionalStackPanel cursor update
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
Labels: size/S, codex

#497 Complete context menu string resources
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
Labels: size/M, codex

#496 Add hide-on-close options
  docs/dock-settings.md
  samples/DockXamlSample/MainView.axaml
  samples/DockXamlSample/MainView.axaml.cs
  src/Dock.Model/Core/Events/DockableHiddenEventArgs.cs
  src/Dock.Model/Core/Events/DockableRestoredEventArgs.cs
  src/Dock.Model/Core/IFactory.Events.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
  src/Dock.Model/FactoryBase.Events.cs
  src/Dock.Model/FactoryBase.Locator.cs
  src/Dock.Settings/DockSettings.cs
Labels: size/L, codex

#507 add a default DockSerializer ctor.
  src/Dock.Serializer/DockSerializer.cs
Labels: size/XS

#500 Add Float All context menu
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/L, codex

#502 Add document dock split options
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/M, codex

#504 Add Dock as Document context option
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
  src/Dock.Avalonia/Converters/OwnerIsToolDockConverter.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/M, codex

#510 Dock on tab strip
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/ToolTabStrip.axaml
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Model/DockManager.cs
Labels: size/M

#503 Add document tab layout options
  src/Dock.Avalonia/Controls/DockDockControl.axaml
  src/Dock.Avalonia/Controls/DocumentControl.axaml
  src/Dock.Avalonia/Controls/DocumentControl.axaml.cs
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ProportionalDockControl.axaml
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Converters/DocumentTabDockConverter.cs
  src/Dock.Avalonia/Converters/DocumentTabOrientationConverter.cs
  src/Dock.Model.Avalonia/Controls/DocumentDock.cs
  src/Dock.Model.Mvvm/Controls/DocumentDock.cs
  src/Dock.Model.ReactiveUI/Controls/DocumentDock.cs
  src/Dock.Model/Controls/IDocumentDock.cs
  src/Dock.Model/Core/DocumentTabLayout.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/L, codex

#516 Update docs for document tab layout
  docs/dock-advanced.md
  docs/dock-enums.md
  docs/dock-reference.md
Labels: size/S, codex

#517 Add DockProperties documentation
  docs/README.md
  docs/dock-properties.md
Labels: size/M, codex

#523 Add DockState usage guide
  docs/README.md
  docs/dock-state.md
Labels: size/M, codex

#524 Add model control docs
  docs/README.md
  docs/dock-model-controls.md
Labels: size/L, codex

#525 Add DockManager documentation
  docs/README.md
  docs/dock-manager-guide.md
Labels: size/M, codex

#526 Implement Notepad menu commands
  samples/Notepad/ViewModels/Documents/FileViewModel.cs
  samples/Notepad/ViewModels/MainWindowViewModel.cs
  samples/Notepad/ViewModels/Tools/FindViewModel.cs
  samples/Notepad/ViewModels/Tools/ReplaceViewModel.cs
  samples/Notepad/Views/Documents/FileView.axaml
  samples/Notepad/Views/MenuView.axaml
Labels: size/L, codex

#530 add a content template the drag preview window.
  src/Dock.Avalonia/Controls/DragPreviewControl.axaml
  src/Dock.Avalonia/Controls/DragPreviewControl.axaml.cs
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DragPreviewHelper.cs
Labels: size/M

#529 Add additional dock panel controls
  docs/dock-enums.md
  docs/dock-model-controls.md
  docs/dock-reference.md
  src/Dock.Avalonia/Controls/DockControl.axaml
  src/Dock.Avalonia/Controls/GridDockControl.axaml
  src/Dock.Avalonia/Controls/GridDockControl.axaml.cs
  src/Dock.Avalonia/Controls/StackDockControl.axaml
  src/Dock.Avalonia/Controls/StackDockControl.axaml.cs
  src/Dock.Avalonia/Controls/UniformGridDockControl.axaml
  src/Dock.Avalonia/Controls/UniformGridDockControl.axaml.cs
  src/Dock.Avalonia/Controls/WrapDockControl.axaml
  src/Dock.Avalonia/Controls/WrapDockControl.axaml.cs
  src/Dock.Avalonia/Themes/DockFluentTheme.axaml
  src/Dock.Avalonia/Themes/DockSimpleTheme.axaml
  src/Dock.Model.Avalonia/Controls/GridDock.cs
  src/Dock.Model.Avalonia/Controls/GridDockSplitter.cs
  src/Dock.Model.Avalonia/Controls/StackDock.cs
  src/Dock.Model.Avalonia/Controls/UniformGridDock.cs
  src/Dock.Model.Avalonia/Controls/WrapDock.cs
  src/Dock.Model.Avalonia/Core/DockBase.cs
  src/Dock.Model.Avalonia/Factory.cs
  src/Dock.Model.Mvvm/Controls/GridDock.cs
  src/Dock.Model.Mvvm/Controls/GridDockSplitter.cs
  src/Dock.Model.Mvvm/Controls/StackDock.cs
  src/Dock.Model.Mvvm/Controls/UniformGridDock.cs
  src/Dock.Model.Mvvm/Controls/WrapDock.cs
  src/Dock.Model.Mvvm/Core/DockBase.cs
  src/Dock.Model.Mvvm/Factory.cs
  src/Dock.Model.ReactiveUI/Controls/GridDock.cs
  src/Dock.Model.ReactiveUI/Controls/GridDockSplitter.cs
  src/Dock.Model.ReactiveUI/Controls/StackDock.cs
  src/Dock.Model.ReactiveUI/Controls/UniformGridDock.cs
  src/Dock.Model.ReactiveUI/Controls/WrapDock.cs
  src/Dock.Model.ReactiveUI/Core/DockBase.cs
  src/Dock.Model.ReactiveUI/Factory.cs
  src/Dock.Model/Controls/IGridDock.cs
  src/Dock.Model/Controls/IGridDockSplitter.cs
  src/Dock.Model/Controls/IStackDock.cs
  src/Dock.Model/Controls/IUniformGridDock.cs
  src/Dock.Model/Controls/IWrapDock.cs
  src/Dock.Model/Core/GridResizeDirection.cs
  src/Dock.Model/Core/IDock.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/DockManager.cs
  src/Dock.Model/FactoryBase.Factory.cs
Labels: size/XXL, codex

#532 Add DockableDocked event
  docs/dock-events.md
  samples/DockMvvmSample/ViewModels/MainWindowViewModel.cs
  samples/DockReactiveUISample/ViewModels/MainWindowViewModel.cs
  src/Dock.Model/Core/Events/DockableDockedEventArgs.cs
  src/Dock.Model/Core/Events/DockableUndockedEventArgs.cs
  src/Dock.Model/Core/IFactory.Events.cs
  src/Dock.Model/FactoryBase.Dockable.cs
  src/Dock.Model/FactoryBase.Events.cs
  src/Dock.Model/FactoryBase.cs
Labels: size/L, codex

#534 offset the position of the drag preview window to give a very smooth ux
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DragPreviewHelper.cs
Labels: size/S

#533 Enable headless Avalonia tests
  build/Avalonia.Headless.props
  tests/Dock.Avalonia.UnitTests/App.axaml
  tests/Dock.Avalonia.UnitTests/App.axaml.cs
  tests/Dock.Avalonia.UnitTests/Controls/ProportionalStackPanelTests.cs
  tests/Dock.Avalonia.UnitTests/Dock.Avalonia.UnitTests.csproj
  tests/Dock.Avalonia.UnitTests/TestAppBuilder.cs
  tests/Dock.Model.Avalonia.UnitTests/App.axaml
  tests/Dock.Model.Avalonia.UnitTests/App.axaml.cs
  tests/Dock.Model.Avalonia.UnitTests/Dock.Model.Avalonia.UnitTests.csproj
  tests/Dock.Model.Avalonia.UnitTests/TestAppBuilder.cs
Labels: size/M, codex

#535 Add headless Dock.Model.Avalonia tests
  tests/Dock.Model.Avalonia.UnitTests/Controls/DockControlsTests.cs
  tests/Dock.Model.Avalonia.UnitTests/FactoryTests.cs
Labels: size/L, codex

#536 Add headless ctor tests for Dock controls
  tests/Dock.Avalonia.UnitTests/Controls/ControlCtorTests.cs
Labels: size/L, codex

#540 Add context menu localization guide
  docs/README.md
  docs/dock-context-menus.md
Labels: size/M, codex

#539 Add drag offset calculator doc
  docs/README.md
  docs/dock-drag-offset-calculator.md
Labels: size/M, codex

#541 Add CanCloseLastDockable menu checks
  docs/dock-context-menus.md
  docs/dock-reference.md
  docs/dock-settings.md
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
  src/Dock.Avalonia/Converters/CanRemoveDockableConverter.cs
  src/Dock.Model.Avalonia/Core/DockBase.cs
  src/Dock.Model.Avalonia/Json/AvaloniaDockSerializer.cs
  src/Dock.Model.Mvvm/Core/DockBase.cs
  src/Dock.Model.ReactiveUI/Core/DockBase.cs
  src/Dock.Model/Core/IDock.cs
  src/Dock.Model/FactoryBase.Dockable.cs
  src/Dock.Model/FactoryBase.Init.cs
Labels: size/L, codex

#548 Add Prism model implementation
  Directory.Packages.props
  Dock.sln
  build/Prism.props
  docs/dock-custom-model.md
  src/Dock.Model.Prism/Controls/DockDock.cs
  src/Dock.Model.Prism/Controls/Document.cs
  src/Dock.Model.Prism/Controls/DocumentDock.cs
  src/Dock.Model.Prism/Controls/GridDock.cs
  src/Dock.Model.Prism/Controls/GridDockSplitter.cs
  src/Dock.Model.Prism/Controls/ProportionalDock.cs
  src/Dock.Model.Prism/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.Prism/Controls/RootDock.cs
  src/Dock.Model.Prism/Controls/StackDock.cs
  src/Dock.Model.Prism/Controls/Tool.cs
  src/Dock.Model.Prism/Controls/ToolDock.cs
  src/Dock.Model.Prism/Controls/UniformGridDock.cs
  src/Dock.Model.Prism/Controls/WrapDock.cs
  src/Dock.Model.Prism/Core/DockBase.cs
  src/Dock.Model.Prism/Core/DockWindow.cs
  src/Dock.Model.Prism/Core/DockableBase.cs
  src/Dock.Model.Prism/Core/ReactiveBase.cs
  src/Dock.Model.Prism/Dock.Model.Prism.csproj
  src/Dock.Model.Prism/Factory.cs
  tests/Dock.Model.Prism.UnitTests/Dock.Model.Prism.UnitTests.csproj
  tests/Dock.Model.Prism.UnitTests/FactoryTests.cs
Labels: size/XXL, codex

#550 Add global docking control option
  docs/dock-settings.md
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Settings/DockSettings.cs
Labels: size/M, codex

#549 Add custom theme guide
  docs/README.md
  docs/dock-custom-theme.md
  docs/dock-styling.md
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/DragPreviewControl.axaml
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia/Themes/Accents/Fluent.axaml
  src/Dock.Avalonia/Themes/Accents/Simple.axaml
Labels: size/L, codex

#551 EnableWindowDrag support
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Model/DockManager.cs
Labels: size/M, codex

#552 Add EnableWindowDrag documentation
  docs/README.md
  docs/dock-window-drag.md
Labels: size/M, codex

#554 when EnableWindowDrag: true, and we are not in a host window, just ca…
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
Labels: size/S

#556 Fix global docking to find proportional dock
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DockHelpers.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
Labels: size/S, codex

#558 Refactor DocumentTabStrip drag
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Controls/HostWindow.axaml
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml.cs
  src/Dock.Avalonia/Internal/WindowDragHelper.cs
Labels: size/L, codex

#559 Annotate template parts and pseudo classes
  src/Dock.Avalonia/Controls/DockTarget.axaml.cs
  src/Dock.Avalonia/Controls/GlobalDockTarget.axaml.cs
  src/Dock.Avalonia/Controls/GridDockControl.axaml.cs
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Avalonia/Controls/HostWindowTitleBar.axaml.cs
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml.cs
Labels: size/M, codex

#561 Update docs for template parts and pseudo classes
  docs/dock-styling.md
Labels: size/S, codex

#565 Expand headless tests
  Dock.sln
  tests/Dock.Avalonia.HeadlessTests/App.axaml
  tests/Dock.Avalonia.HeadlessTests/App.axaml.cs
  tests/Dock.Avalonia.HeadlessTests/Dock.Avalonia.HeadlessTests.csproj
  tests/Dock.Avalonia.HeadlessTests/DockControlInstantiationTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockControlTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockControlsTests.cs
  tests/Dock.Avalonia.HeadlessTests/DocumentDockNewDockTests.cs
  tests/Dock.Avalonia.HeadlessTests/DocumentDockPropertiesTests.cs
  tests/Dock.Avalonia.HeadlessTests/DocumentDockTemplateTests.cs
  tests/Dock.Avalonia.HeadlessTests/DocumentTabStripItemAndThemeTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryDockableLifecycleTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryDockableTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryPinAlignmentTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryPinTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryWindowManagementTests.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryWindowTests.cs
  tests/Dock.Avalonia.HeadlessTests/PreviewPinnedDockTests.cs
  tests/Dock.Avalonia.HeadlessTests/Properties/AssemblyInfo.cs
  tests/Dock.Avalonia.HeadlessTests/TestAppBuilder.cs
Labels: size/XXL, codex

#566 Add headless split tests
  src/Dock.Model/FactoryBase.Locator.cs
  tests/Dock.Avalonia.HeadlessTests/App.axaml.cs
  tests/Dock.Avalonia.HeadlessTests/FactorySplitTests.cs
Labels: size/L, codex

#569 Implement dock target visibility API
  docs/dock-manager-guide.md
  src/Dock.Avalonia/Controls/DockTarget.axaml.cs
  src/Dock.Avalonia/Controls/GlobalDockTarget.axaml.cs
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Model/Core/IDockManager.cs
  src/Dock.Model/DockManager.cs
Labels: size/L, codex

#567 Expand coverage for Dock states
  src/Dock.Avalonia/Dock.Avalonia.csproj
  tests/Dock.Avalonia.HeadlessTests/Dock.Avalonia.HeadlessTests.csproj
  tests/Dock.Avalonia.HeadlessTests/DockControlStateTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockManagerTests.cs
  tests/Dock.Avalonia.HeadlessTests/HostWindowStateTests.cs
Labels: size/L, codex

#575 Fix WebViewSample package conditions
  samples/WebViewSample/WebViewSample.csproj
Labels: size/XS, codex

#578 Add more headless tests
  tests/Dock.Avalonia.HeadlessTests/DockHelpersTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockManagerDocumentTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockWindowTests.cs
  tests/Dock.Avalonia.HeadlessTests/DocumentDockCommandTests.cs
Labels: size/L, codex

#589 Add missing headless tests
  tests/Dock.Avalonia.HeadlessTests/ConvertersTests.cs
  tests/Dock.Avalonia.HeadlessTests/HostWindowMethodsTests.cs
Labels: size/L, codex

#586 Add code-only sample app
  Dock.sln
  docs/dock-code-only.md
  docs/dock-reference.md
  samples/DockCodeOnlySample/DockCodeOnlySample.csproj
  samples/DockCodeOnlySample/Program.cs
Labels: size/L, codex

#583 Add floating pinned window fixes
  docs/README.md
  docs/dock-pinned-window.md
  src/Dock.Avalonia/Controls/PinnedDockControl.axaml
  src/Dock.Avalonia/Controls/PinnedDockControl.axaml.cs
  src/Dock.Avalonia/Controls/PinnedDockWindow.axaml
  src/Dock.Avalonia/Controls/PinnedDockWindow.axaml.cs
  src/Dock.Avalonia/Themes/DockFluentTheme.axaml
  src/Dock.Avalonia/Themes/DockSimpleTheme.axaml
  src/Dock.Settings/AppBuilderExtensions.cs
  src/Dock.Settings/DockSettings.cs
  src/Dock.Settings/DockSettingsOptions.cs
Labels: size/L, codex

#590 Add AddDocument helper to DocumentDock
  samples/DockCodeOnlySample/Program.cs
  samples/Notepad/ViewModels/Docks/FilesDocumentDock.cs
  samples/Notepad/ViewModels/MainWindowViewModel.cs
  samples/Notepad/ViewModels/NotepadFactory.cs
  src/Dock.Model.Avalonia/Controls/DocumentDock.cs
  src/Dock.Model.Mvvm/Controls/DocumentDock.cs
  src/Dock.Model.Prism/Controls/DocumentDock.cs
  src/Dock.Model.ReactiveUI/Controls/DocumentDock.cs
Labels: size/L, codex

#598 Add IndicatorDockOperation property
  docs/dock-properties.md
  src/Dock.Avalonia/Controls/DockTarget.axaml.cs
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/GlobalDockTarget.axaml.cs
  src/Dock.Avalonia/Controls/ToolTabStrip.axaml
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Settings/DockProperties.cs
Labels: size/L, codex

#595 Add indicator-only dock targets for tab strips
  docs/dock-properties.md
  src/Dock.Avalonia/Controls/DockTarget.axaml
  src/Dock.Avalonia/Controls/DockTarget.axaml.cs
  src/Dock.Avalonia/Controls/DocumentControl.axaml
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Controls/GlobalDockTarget.axaml
  src/Dock.Avalonia/Controls/GlobalDockTarget.axaml.cs
  src/Dock.Avalonia/Controls/ToolControl.axaml
  src/Dock.Avalonia/Controls/ToolTabStrip.axaml
  src/Dock.Avalonia/Controls/ToolTabStrip.axaml.cs
  src/Dock.Avalonia/Internal/AdornerHelper.cs
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Settings/DockProperties.cs
Labels: size/L, codex

#600 Update docs for DockTargetBase
  docs/dock-deep-dive.md
  docs/dock-properties.md
  docs/dock-settings-controls.md
  docs/dock-settings.md
  src/Dock.Avalonia/Controls/DockTargetBase.cs
Labels: size/M, codex

#601 Add dock target headless tests
  tests/Dock.Avalonia.HeadlessTests/DockTargetTests.cs
Labels: size/M, codex

#603 Add floating window owner setting
  docs/README.md
  docs/dock-settings.md
  docs/dock-window-owner.md
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Settings/AppBuilderExtensions.cs
  src/Dock.Settings/DockSettings.cs
  src/Dock.Settings/DockSettingsOptions.cs
Labels: size/M, codex

#610 Guard against drop on unsupported dock targets
  src/Dock.Model/DockManager.cs
Labels: size/M

#628 Add tests for ControlRecycling
  Dock.sln
  tests/Dock.Controls.Recycling.UnitTests/App.axaml
  tests/Dock.Controls.Recycling.UnitTests/App.axaml.cs
  tests/Dock.Controls.Recycling.UnitTests/Controls/ControlRecyclingDataTemplateTests.cs
  tests/Dock.Controls.Recycling.UnitTests/Controls/ControlRecyclingTests.cs
  tests/Dock.Controls.Recycling.UnitTests/Dock.Controls.Recycling.UnitTests.csproj
  tests/Dock.Controls.Recycling.UnitTests/TestAppBuilder.cs
Labels: size/L, codex

#620 Add ReactiveUI tests
  tests/Dock.Model.ReactiveUI.UnitTests/Controls/DockControlsTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/Controls/DocumentDockActionsTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/DockWindowTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/DockableTrackingTests.cs
Labels: size/L, codex

#622 Add Dock.Settings unit tests
  tests/Dock.Settings.UnitTests/AppBuilderExtensionsTests.cs
  tests/Dock.Settings.UnitTests/Dock.Settings.UnitTests.csproj
  tests/Dock.Settings.UnitTests/DockPropertiesTests.cs
  tests/Dock.Settings.UnitTests/DockSettingsTests.cs
  tests/Dock.Settings.UnitTests/Properties/AssemblyInfo.cs
  tests/Dock.Settings.UnitTests/TestAppBuilder.cs
Labels: size/L, codex

#625 Add XML serializer
  Dock.sln
  src/Dock.Serializer.Xml/Dock.Serializer.Xml.csproj
  src/Dock.Serializer.Xml/DockXmlSerializer.cs
Labels: size/L, codex

#623 Add System.Text.Json serializer project
  Dock.sln
  src/Dock.Serializer.SystemTextJson/Dock.Serializer.SystemTextJson.csproj
  src/Dock.Serializer.SystemTextJson/DockSerializer.cs
Labels: size/L, codex

#614 Add tests for control recycling interfaces
  Dock.sln
  tests/Dock.Controls.Recycling.Model.UnitTests/ControlRecyclingTests.cs
  tests/Dock.Controls.Recycling.Model.UnitTests/Dock.Controls.Recycling.Model.UnitTests.csproj
  tests/Dock.Controls.Recycling.Model.UnitTests/DummyControlRecycling.cs
  tests/Dock.Controls.Recycling.Model.UnitTests/Properties/AssemblyInfo.cs
Labels: size/L, codex

#636 Implement list type support across serializers
  src/Dock.Serializer.Protobuf/ListTypeConverter.cs
  src/Dock.Serializer.Protobuf/ProtobufDockSerializer.cs
  src/Dock.Serializer.Xml/DockXmlSerializer.cs
  src/Dock.Serializer.Xml/ListTypeConverter.cs
  src/Dock.Serializer.Yaml/DockYamlSerializer.cs
  src/Dock.Serializer.Yaml/ListTypeConverter.cs
  tests/Dock.Serializer.UnitTests/Dock.Serializer.UnitTests.csproj
  tests/Dock.Serializer.UnitTests/ProtobufDockSerializerTests.cs
  tests/Dock.Serializer.UnitTests/XmlDockSerializerTests.cs
  tests/Dock.Serializer.UnitTests/YamlDockSerializerTests.cs
Labels: size/L, codex

#635 Add ReactiveUI DI sample
  Directory.Packages.props
  Dock.sln
  samples/DockReactiveUIDiSample/App.axaml
  samples/DockReactiveUIDiSample/App.axaml.cs
  samples/DockReactiveUIDiSample/DockReactiveUIDiSample.csproj
  samples/DockReactiveUIDiSample/Models/DemoData.cs
  samples/DockReactiveUIDiSample/Program.cs
  samples/DockReactiveUIDiSample/ViewModels/DockFactory.cs
  samples/DockReactiveUIDiSample/ViewModels/DocumentViewModel.cs
  samples/DockReactiveUIDiSample/ViewModels/MainWindowViewModel.cs
  samples/DockReactiveUIDiSample/ViewModels/ToolViewModel.cs
  samples/DockReactiveUIDiSample/Views/MainWindow.axaml
  samples/DockReactiveUIDiSample/Views/MainWindow.axaml.cs
Labels: size/L, codex

#643 Add DI helper for Dock
  Dock.sln
  build/Microsoft.Extensions.DependencyInjection.props
  docs/README.md
  docs/dock-dependency-injection.md
  src/Dock.Model.Extensions.DependencyInjection/Dock.Model.Extensions.DependencyInjection.csproj
  src/Dock.Model.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
Labels: size/M, codex

#644 Fix DI view locator implementation
  samples/DockReactiveUIDiSample/App.axaml
  samples/DockReactiveUIDiSample/App.axaml.cs
  samples/DockReactiveUIDiSample/Program.cs
  samples/DockReactiveUIDiSample/ViewLocator.cs
Labels: size/S, codex

#673 Use reactive base classes in DI sample
  samples/DockReactiveUIDiSample/Views/Documents/DocumentView.axaml.cs
  samples/DockReactiveUIDiSample/Views/MainWindow.axaml.cs
  samples/DockReactiveUIDiSample/Views/Tools/ToolView.axaml.cs
Labels: size/M, codex

#672 Improve ReactiveUI DI sample
  .nuke/build.schema.json
  samples/DockReactiveUIDiSample/App.axaml.cs
  samples/DockReactiveUIDiSample/Program.cs
  samples/DockReactiveUIDiSample/ViewLocator.cs
  samples/DockReactiveUIDiSample/Views/Documents/DocumentView.axaml.cs
  samples/DockReactiveUIDiSample/Views/MainWindow.axaml.cs
  samples/DockReactiveUIDiSample/Views/Tools/ToolView.axaml.cs
Labels: size/L, codex

#680 calculate the offset into the drag preview, based on the pointer pressed position
  src/Dock.Avalonia/Internal/DockControlState.cs
Labels: size/XS

#684 Allow the window to be dragged by the last tab
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
Labels: size/M

#687 Prevent local value being set on Window.Title preventing binding to FocusedDockable.Title
  src/Dock.Avalonia/Controls/HostWindow.axaml
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Model/Core/IHostWindow.cs
Labels: size/S

#765 Add converter for TreeView title fallback
  src/Dock.Avalonia/Controls/RootDockDebug.axaml
  src/Dock.Avalonia/Converters/TitleOrTypeNameConverter.cs
Labels: size/L, codex

#759 Enhance debug tooling
  docs/README.md
  docs/dock-root-dock-debug.md
  samples/DockInpcSample/App.axaml.cs
  samples/DockMvvmSample/App.axaml.cs
  samples/DockReactiveUIDiSample/App.axaml.cs
  samples/DockReactiveUIRoutingSample/App.axaml.cs
  samples/DockReactiveUISample/App.axaml.cs
  samples/Notepad/App.axaml.cs
  src/Dock.Avalonia/Controls/ControlStrings.axaml
  src/Dock.Avalonia/Controls/RootDockDebug.axaml
  src/Dock.Avalonia/Controls/RootDockDebug.axaml.cs
  src/Dock.Avalonia/Controls/RootDockDebugExtensions.cs
  src/Dock.Avalonia/Converters/TitleOrTypeNameConverter.cs
Labels: size/XL, codex

#679 Fix OnClose not triggered for floating documents
  global.json
  src/Dock.Model.Avalonia/Core/DockWindow.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Window.cs
Labels: size/M, codex

#758 Add resize preview option for dock splitter
  docs/dock-model-controls.md
  docs/dock-reference.md
  docs/dock-sizing.md
  samples/DockMvvmSample/ViewModels/DockFactory.cs
  src/Dock.Avalonia/Controls/DockControl.axaml
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
  src/Dock.Model.Avalonia/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.Mvvm/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.Prism/Controls/ProportionalDockSplitter.cs
  src/Dock.Model.ReactiveUI/Controls/ProportionalDockSplitter.cs
  src/Dock.Model/Controls/IProportionalDockSplitter.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DockControlsTests.cs
  tests/Dock.Model.Avalonia.UnitTests/FactoryTests.cs
  tests/Dock.Model.Mvvm.UnitTests/FactoryTests.cs
  tests/Dock.Model.Prism.UnitTests/FactoryTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/FactoryTests.cs
Labels: size/L, codex

#756 Add dynamic dock debug overlay
  docs/README.md
  docs/dock-debug-overlay.md
  samples/DockMvvmSample/Views/MainWindow.axaml.cs
  src/Dock.Avalonia/Controls/DebugOverlayAdorner.cs
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Diagnostics/DockDebugOverlayExtensions.cs
  src/Dock.Avalonia/Diagnostics/DockDebugOverlayManager.cs
  src/Dock.Avalonia/Internal/DebugOverlayHelper.cs
  src/Dock.Settings/AppBuilderExtensions.cs
  src/Dock.Settings/DockSettings.cs
  src/Dock.Settings/DockSettingsOptions.cs
  tests/Dock.Settings.UnitTests/AppBuilderExtensionsTests.cs
Labels: size/L, codex

#748 Allow UserControl document content
  docs/dock-code-only.md
  src/Dock.Model.Avalonia/Controls/TemplateHelper.cs
  tests/Dock.Avalonia.HeadlessTests/FactoryDockableTests.cs
Labels: size/M, codex

#768 Fix preview z-index on splitter
  samples/DockMvvmSample/ViewModels/DockFactory.cs
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
  src/Dock.Controls.ProportionalStackPanel/SplitterPreviewAdorner.cs
Labels: size/M, codex

#769 Fix debug overlay flicker
  src/Dock.Avalonia/Controls/Diagnostics/DebugOverlayAdorner.cs
Labels: size/XS, codex

#771 Fix debug overlay enumeration
  src/Dock.Avalonia/Diagnostics/DockDebugOverlayManager.cs
Labels: size/XS, codex

#773 Fix tab strip items padding
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml
Labels: size/L

#744 Add guide for displaying dock views
  docs/README.md
  docs/dock-views.md
  docs/quick-start.md
Labels: size/M, codex

#706 Add IDockService interface and update DockManager
  docs/dock-deep-dive.md
  docs/dock-manager-guide.md
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Model/Core/IDockService.cs
  src/Dock.Model/DockManager.cs
  src/Dock.Model/DockService.cs
  tests/Dock.Avalonia.HeadlessTests/DockControlStateTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockManagerDocumentTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockManagerTests.cs
  tests/Dock.Avalonia.HeadlessTests/HostWindowStateTests.cs
Labels: size/L, codex

#775 Add note to use Dock.Model.Avalonia for RootDock, etc.
  docs/quick-start.md
Labels: size/S

#786 Fix dialog warnings
  samples/Notepad/ViewModels/MainWindowViewModel.cs
Labels: size/M

#788 fix flickering when dragging over tabstrip items
  src/Dock.Avalonia/Internal/AdornerHelper.cs
Labels: size/S

#789 Add AdornerHelper tests
  src/Dock.Avalonia/Dock.Avalonia.csproj
  tests/Dock.Avalonia.HeadlessTests/AdornerHelperTests.cs
  tests/Dock.Avalonia.UnitTests/AdornerHelperTests.cs
  tests/Dock.Avalonia.UnitTests/Dock.Avalonia.UnitTests.csproj
Labels: size/M

#793 window drag helper fix dragging by the main window on win32
  src/Dock.Avalonia/Internal/WindowDragHelper.cs
Labels: size/XS

#791 Bring windows to front on drag
  docs/dock-settings.md
  docs/dock-windows.md
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Avalonia/Internal/WindowActivationHelper.cs
  src/Dock.Avalonia/Internal/WindowDragHelper.cs
  src/Dock.Settings/AppBuilderExtensions.cs
  src/Dock.Settings/DockSettings.cs
  src/Dock.Settings/DockSettingsOptions.cs
Labels: size/L

#795 Enable floating via tab double-click
  docs/dock-faq.md
  src/Dock.Avalonia/Controls/DocumentTabStripItem.axaml.cs
  src/Dock.Avalonia/Controls/ToolTabStripItem.axaml.cs
Labels: size/S, codex

#800 Improve diagnostics tools with adorned overlay
  src/Dock.Avalonia.Diagnostics/Controls/RootDockDebug.axaml.cs
  src/Dock.Avalonia.Diagnostics/Controls/SelectionOverlayAdorner.cs
  src/Dock.Avalonia.Diagnostics/Helpers/SelectionOverlayHelper.cs
Labels: size/L

#801 Refactor dock target base class
  src/Dock.Avalonia/Controls/DockTargetBase.cs
Labels: size/L

#802 fix docktarget not getting its state reset when being reused.
  .gitignore
  src/Dock.Avalonia/Controls/DockTargetBase.cs
  src/Dock.Avalonia/Controls/IDockTarget.cs
  src/Dock.Avalonia/Internal/AdornerHelper.cs
Labels: size/M

#809 Fix debug overlay hotkey
  docs/dock-debug-overlay.md
Labels: size/XS, codex

#813 fix win32 issues with dragging by the document tab strip.
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml.cs
  src/Dock.Avalonia/Internal/WindowDragHelper.cs
Labels: size/M

#814 fix windowdraghandler dragging the whole window.
  src/Dock.Avalonia/Controls/DocumentTabStrip.axaml.cs
  src/Dock.Avalonia/Controls/ToolChromeControl.axaml.cs
  src/Dock.Avalonia/Internal/WindowDragHelper.cs
Labels: size/M

#816 fix documents docking into tool area.
  src/Dock.Model/DockManager.cs
Labels: size/XS

#821 Add CloseTemplate for DocumentControl
  src/Dock.Avalonia.Themes.Fluent/Controls/DocumentControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia/Controls/DocumentControl.axaml.cs
Labels: size/L

#824 Fix control recycling
  src/Dock.Controls.Recycling/ControlRecycling.cs
  tests/Dock.Controls.Recycling.UnitTests/Controls/ControlRecyclingTests.cs
Labels: size/M

#826 Fix pinned dockable serialization
  src/Dock.Model/FactoryBase.Dockable.cs
  src/Dock.Model/FactoryBase.Init.cs
  tests/Dock.Avalonia.HeadlessTests/PreviewPinnedDockTests.cs
Labels: size/M

#827 Add DocumentDock.ItemsSource support
  docs/ITEMSSOURCE_MIGRATION_GUIDE.md
  docs/README.md
  docs/dock-content-guide.md
  docs/dock-content-wrapper-pattern.md
  docs/dock-faq.md
  docs/dock-views.md
  samples/DockXamlSample/ItemsSourceExample.axaml
  samples/DockXamlSample/ItemsSourceExample.axaml.cs
  samples/DockXamlSample/ItemsSourceExampleViewModel.cs
  samples/DockXamlSample/ItemsSourceExampleWindow.axaml
  samples/DockXamlSample/ItemsSourceExampleWindow.axaml.cs
  samples/DockXamlSample/MainView.axaml
  samples/DockXamlSample/MainView.axaml.cs
  samples/DockXamlSample/MyDocumentModel.cs
  src/Dock.Model.Avalonia/Controls/DocumentDock.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceActiveDocumentTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceFallbackTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceNamespaceTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceSampleTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceUITests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceXamlDebugTests.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceXamlTests.cs
Labels: size/XXL

#831 Enable drag and drop for ToolPinItemControl
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolPinItemControl.axaml
  src/Dock.Model/DockManager.cs
  src/Dock.Model/FactoryBase.Dockable.cs
  tests/Dock.Avalonia.HeadlessTests/PinnedDockDragDropTests.cs
Labels: size/XL

#833 Drag pinned dockables
  src/Dock.Avalonia.Themes.Fluent/Controls/RootDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolPinnedControl.axaml
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolPinItemControl.axaml.cs
  src/Dock.Avalonia/Controls/ToolPinnedControl.axaml.cs
  src/Dock.Avalonia/Internal/ItemDragHelper.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/L

#835 initial implementation for window activation from the model.
  samples/DockInpcSample/ViewModels/MainWindowViewModel.cs
  samples/DockMvvmSample/ViewModels/MainWindowViewModel.cs
  samples/DockReactivePropertySample/ViewModels/MainWindowViewModel.cs
  samples/DockReactiveUISample/ViewModels/MainWindowViewModel.cs
  src/Dock.Avalonia.Diagnostics/Controls/RootDockDebug.axaml.cs
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Model.Avalonia/Core/DockWindow.cs
  src/Dock.Model.Inpc/Core/DockWindow.cs
  src/Dock.Model.Mvvm/Core/DockWindow.cs
  src/Dock.Model.Prism/Core/DockWindow.cs
  src/Dock.Model.ReactiveProperty/Core/DockWindow.cs
  src/Dock.Model.ReactiveUI/Core/DockWindow.cs
  src/Dock.Model/Adapters/HostAdapter.cs
  src/Dock.Model/Core/Events/DockableActivatedEventArgs.cs
  src/Dock.Model/Core/Events/DockableDeactivatedEventArgs.cs
  src/Dock.Model/Core/Events/WindowActivatedEventArgs.cs
  src/Dock.Model/Core/Events/WindowDeactivatedEventArgs.cs
  src/Dock.Model/Core/IDockWindow.cs
  src/Dock.Model/Core/IFactory.Events.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/Core/IHostAdapter.cs
  src/Dock.Model/Core/IHostWindow.cs
  src/Dock.Model/FactoryBase.Events.cs
  src/Dock.Model/FactoryBase.Init.cs
  tests/Dock.Model.Avalonia.UnitTests/FactoryTests.cs
  tests/Dock.Model.Mvvm.UnitTests/FactoryTests.cs
  tests/Dock.Model.Prism.UnitTests/DockWindowTests.cs
  tests/Dock.Model.Prism.UnitTests/FactoryTests.cs
  tests/Dock.Model.ReactiveProperty.UnitTests/FactoryTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/DockWindowTests.cs
  tests/Dock.Model.ReactiveUI.UnitTests/FactoryTests.cs
Labels: size/XXL

#839 Dynamic Resource for Menu Button on ToolChromeControl
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolChromeControl.axaml
Labels: size/XS

#837 Control users main window from the model
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Controls/HostWindow.axaml.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/Core/IHostWindow.cs
  src/Dock.Model/FactoryBase.Init.cs
  tests/Dock.Avalonia.Diagnostics.UnitTests/DockControlInstantiationTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockControlMainWindowTests.cs
Labels: size/L
