Repository wieslawsoltes/Dock, pull requests merged in 2025-08, with the labels that each got.

#850 Allow using control for Tool and Document content
  samples/DockCodeOnlySample/Program.cs
  src/Dock.Model.Avalonia/Controls/TemplateHelper.cs
Labels: size/S

#851 Sync ItemsSource
  src/Dock.Model.Avalonia/Controls/DocumentDock.cs
  src/Dock.Model/Core/IItemsSourceDock.cs
  src/Dock.Model/FactoryBase.Dockable.cs
  tests/Dock.Model.Avalonia.UnitTests/Controls/DocumentDockItemsSourceSampleTests.cs
Labels: size/L

#858 Add DocumentDock ItemsSource docs
  docs/ITEMSSOURCE_MIGRATION_GUIDE.md
  docs/README.md
  docs/dock-itemssource.md
Labels: size/XL

#855 Docking groups
  Dock.sln
  docs/README.md
  docs/dock-architecture.md
  docs/dock-dockable-properties.md
  docs/dock-docking-groups.md
  docs/dock-faq.md
  docs/dock-manager-guide.md
  docs/dock-mvvm.md
  docs/dock-properties.md
  samples/DockMvvmSample/ViewModels/DockFactory.cs
  src/Dock.Avalonia.Themes.Fluent/Controls/DockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/DockDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/DocumentControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/DocumentDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/DocumentTabStripItem.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/GridDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/HostWindow.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/PinnedDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ProportionalDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/RootDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/StackDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolChromeControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolPinItemControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolPinnedControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolTabStrip.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolTabStripItem.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/UniformGridDockControl.axaml
  src/Dock.Avalonia.Themes.Fluent/Controls/WrapDockControl.axaml
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Model.Avalonia/Core/DockableBase.cs
  src/Dock.Model.Inpc/Core/DockableBase.cs
  src/Dock.Model.Mvvm/Core/DockableBase.cs
  src/Dock.Model.Prism/Core/DockableBase.cs
  src/Dock.Model.ReactiveProperty/Core/DockableBase.cs
  src/Dock.Model.ReactiveUI/Core/DockableBase.cs
  src/Dock.Model/Core/DockGroupValidator.cs
  src/Dock.Model/Core/IDockable.cs
  src/Dock.Model/DockManager.cs
  src/Dock.Model/DockService.cs
  src/Dock.Settings/DockProperties.cs
  tests/Dock.Avalonia.HeadlessTests/DockGroupHeadlessTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockGroupThemeBindingTests.cs
  tests/Dock.Avalonia.HeadlessTests/GlobalDockingValidationTests.cs
  tests/Dock.Avalonia.UnitTests/DockGroupAttachedPropertyTests.cs
  tests/Dock.Model.UnitTests/Dock.Model.UnitTests.csproj
  tests/Dock.Model.UnitTests/DockGroupValidationTests.cs
  tests/Dock.Settings.UnitTests/DockGroupTests.cs
Labels: size/XXL

#860 Refactor proportional panel
  src/Dock.Controls.ProportionalStackPanel/Internal/ConstraintCalculator.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/DimensionCalculator.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/PanelNavigationHelper.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/ProportionConstraintHandler.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/ProportionManager.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/ProportionResizer.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/ProportionUtils.cs
  src/Dock.Controls.ProportionalStackPanel/Internal/SplitterCalculator.cs
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanel.cs
  src/Dock.Controls.ProportionalStackPanel/ProportionalStackPanelSplitter.axaml.cs
Labels: size/XXL

#863 Fix the proportions applied when splitting
  src/Dock.Avalonia.Themes.Fluent/Controls/ProportionalDockControl.axaml
  src/Dock.Avalonia/Controls/ProportionalDockControl.axaml.cs
Labels: size/M

#859 Optimize split layout
  src/Dock.Model/FactoryBase.Dockable.cs
  src/Dock.Model/FactoryBase.cs
  tests/Dock.Avalonia.HeadlessTests/FactorySplitTests.cs
  tests/Dock.Avalonia.HeadlessTests/OptimizedSplitLayoutTests.cs
  tests/Dock.Avalonia.HeadlessTests/OptimizedSplitLayoutUITests.cs
Labels: size/XXL

#867 Use default host window locator
  Dock.sln
  samples/DockSimplifiedSample/App.axaml
  samples/DockSimplifiedSample/App.axaml.cs
  samples/DockSimplifiedSample/DockSimplifiedSample.csproj
  samples/DockSimplifiedSample/MainWindow.axaml
  samples/DockSimplifiedSample/MainWindow.axaml.cs
  samples/DockSimplifiedSample/Program.cs
  src/Dock.Model.Avalonia/Factory.cs
  src/Dock.Model/FactoryBase.Init.cs
Labels: size/L

#871 Create data templates from code behind for DockControl
  docs/README.md
  docs/dock-datatemplates.md
  src/Dock.Avalonia.Themes.Fluent/Controls/DockControl.axaml
  src/Dock.Avalonia/Controls/DockControl.axaml.cs
  src/Dock.Avalonia/Internal/DockDataTemplateHelper.cs
  src/Dock.Model/Controls/IDockDock.cs
  src/Dock.Model/Controls/IDocumentContent.cs
  src/Dock.Model/Controls/IDocumentDock.cs
  src/Dock.Model/Controls/IGridDock.cs
  src/Dock.Model/Controls/IGridDockSplitter.cs
  src/Dock.Model/Controls/IProportionalDock.cs
  src/Dock.Model/Controls/IProportionalDockSplitter.cs
  src/Dock.Model/Controls/IRootDock.cs
  src/Dock.Model/Controls/IStackDock.cs
  src/Dock.Model/Controls/IToolContent.cs
  src/Dock.Model/Controls/IToolDock.cs
  src/Dock.Model/Controls/IUniformGridDock.cs
  src/Dock.Model/Controls/IWrapDock.cs
  src/Dock.Model/Core/RequiresDataTemplateAttribute.cs
  tests/Dock.Avalonia.HeadlessTests/DockControlDataTemplateTests.cs
  tests/Dock.Avalonia.HeadlessTests/DockGroupHeadlessTests.cs
  tests/Dock.Avalonia.HeadlessTests/OptimizedSplitLayoutUITests.cs
  tests/Dock.Avalonia.UnitTests/Helpers/DockDataTemplateHelperTests.cs
Labels: size/XL

#874 Do drag offset calculation on all controls not just tabstripitems
  src/Dock.Avalonia/Internal/DefaultDragOffsetCalculator.cs
Labels: size/XS

#875 only set IsDraggingDock when a drag operation has actually started.
  src/Dock.Avalonia/Internal/DockControlState.cs
Labels: size/XS

#876 Fix: Dont crash if docktarget ApplyTemplate is called multiple times
  src/Dock.Avalonia/Controls/DockTargetBase.cs
Labels: size/XS

#877 Ensure dockable properties are updated before firing Docked and Moved events
  src/Dock.Model/FactoryBase.Dockable.cs
Labels: size/XS

#878 allow the user to drop into an empty tooldock.
  src/Dock.Avalonia.Themes.Fluent/Controls/ToolDockControl.axaml
Labels: size/XS

#882 ensure we always obey the IDockable.CanFloat setting.
  src/Dock.Avalonia/Internal/DockControlState.cs
Labels: size/XS

#883 Move global dock setting into IDock
  docs/dock-settings.md
  samples/DockInpcSample/Program.cs
  samples/DockMvvmSample/Program.cs
  samples/DockMvvmSample/ViewModels/DockFactory.cs
  samples/DockReactivePropertySample/Program.cs
  samples/DockReactiveUISample/Program.cs
  samples/DockXamlSample/Program.cs
  samples/Notepad/Program.cs
  samples/WebViewSample/Program.cs
  src/Dock.Avalonia/Internal/DockControlState.cs
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Avalonia/Internal/HostWindowState.cs
  src/Dock.Model.Avalonia/Core/DockBase.cs
  src/Dock.Model.Inpc/Core/DockBase.cs
  src/Dock.Model.Mvvm/Core/DockBase.cs
  src/Dock.Model.Prism/Core/DockBase.cs
  src/Dock.Model.ReactiveProperty/Core/DockBase.cs
  src/Dock.Model.ReactiveUI/Core/DockBase.cs
  src/Dock.Model/Core/DockGroupValidator.cs
  src/Dock.Model/Core/DockInheritanceHelper.cs
  src/Dock.Model/Core/IDock.cs
  src/Dock.Settings/AppBuilderExtensions.cs
  src/Dock.Settings/DockSettings.cs
  src/Dock.Settings/DockSettingsOptions.cs
  tests/Dock.Avalonia.HeadlessTests/GlobalDockingInheritanceTests.cs
  tests/Dock.Avalonia.HeadlessTests/GlobalDockingValidationTests.cs
  tests/Dock.Model.UnitTests/DockGroupValidationTests.cs
  tests/Dock.Settings.UnitTests/AppBuilderExtensionsTests.cs
Labels: size/L

#887 Tree Cleanup
  src/Dock.Model/FactoryBase.cs
  tests/Dock.Avalonia.HeadlessTests/FactorySplitTests.cs
Labels: size/M

#890 Fluent extensions
  Dock.sln
  docs/dock-fluent-extensions.md
  samples/DockCodeOnlyMvvmSample/DockCodeOnlyMvvmSample.csproj
  samples/DockCodeOnlyMvvmSample/Program.cs
  samples/DockSimplifiedFluentSample/App.axaml
  samples/DockSimplifiedFluentSample/App.axaml.cs
  samples/DockSimplifiedFluentSample/DockSimplifiedFluentSample.csproj
  samples/DockSimplifiedFluentSample/MainWindow.axaml
  samples/DockSimplifiedFluentSample/MainWindow.axaml.cs
  samples/DockSimplifiedFluentSample/Program.cs
  src/Dock.Model.Avalonia/Factory.cs
  src/Dock.Model.CaliburMicro/Factory.cs
  src/Dock.Model.Inpc/Factory.cs
  src/Dock.Model.Mvvm/Factory.cs
  src/Dock.Model.Prism/Factory.cs
  src/Dock.Model.ReactiveProperty/Factory.cs
  src/Dock.Model.ReactiveUI/Factory.cs
  src/Dock.Model/Core/IFactory.cs
  src/Dock.Model/FactoryBase.Factory.cs
  src/Dock.Model/FluentExtensions.cs
Labels: size/XXL

#885 Intelligently offer the global docking options
  docs/dock-properties.md
  src/Dock.Avalonia.Themes.Fluent/Controls/GlobalDockTarget.axaml
  src/Dock.Avalonia/Controls/DockTargetBase.cs
  src/Dock.Avalonia/Internal/AdornerHelper.cs
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Avalonia/Internal/GlobalDockingHelper.cs
  src/Dock.Model.Avalonia/Controls/RootDock.cs
  src/Dock.Model.Inpc/Controls/RootDock.cs
  src/Dock.Model.Mvvm/Controls/RootDock.cs
  src/Dock.Model.Prism/Controls/RootDock.cs
  src/Dock.Model.ReactiveProperty/Controls/RootDock.cs
  src/Dock.Model.ReactiveUI/Controls/RootDock.cs
  src/Dock.Model/Controls/IRootDock.cs
  src/Dock.Model/FactoryBase.cs
Labels: size/L

#892 Fix dock group validation
  src/Dock.Avalonia/Internal/DockManagerState.cs
  src/Dock.Model/DockService.cs
  tests/Dock.Avalonia.HeadlessTests/DockGroupExecutionTests.cs
Labels: size/L
